### PR TITLE
vs2017-professional: sample chocolatey package helper for orgs

### PR DESCRIPTION
**Pull request by rismoney**
Summary: installing vs2017 is not so simple for your organization
This provides some tools to assist with creating a choco package
that creates a defined installation with workloads and options
of your choosing

### CODE REVIEW

**Review by ferventcoder — CHANGES_REQUESTED** [review]
Pull out the binaries from the repo unless they have free distro rights. If they do, drop the licenses in here. Provide links for folks to go get them (I know it sucks, but legal)

**Comment by ferventcoder** [comment]
Looks good otherwise!

**Comment by rismoney** [comment]
binaries resected and readme updated with refs as distro rights are uncertain atm.

**Review by ferventcoder — APPROVED** [review]
Looks like a great start!

**Pull request merged**
